package com.financeos.financeosbackend.notification.event;

public enum FinancialEventType {

    INVESTMENT_UPDATED,

    DAILY_INVESTMENT_UPDATE,

    GOAL_PROGRESS_CHANGED,

    GOAL_FALLING_BEHIND,

    EXPENSE_REQUIRES_ATTENTION,

    TRANSACTION_REQUIRES_REVIEW,

    HELP_RETURN_REQUIRED,

    LIABILITY_PAYMENT_DUE,

    LIABILITY_PAYMENT_OVERDUE,

    CASH_FLOW_ALERT,

    FINANCIAL_HEALTH_CHANGED,

    MARKET_ALERT,

    INSURANCE_EXPIRING,

    FINANCIAL_EVENT_UPCOMING,

    DAILY_FINANCIAL_UPDATE
}