package com.financeos.financeosbackend.reporting.pdf;

import com.financeos.financeosbackend.reporting.dto.FinancialReportResponse;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Service
public class PdfReportService {

    private static final Logger logger =
            LoggerFactory.getLogger(PdfReportService.class);

    public byte[] generatePdf(FinancialReportResponse report) {

        logger.info("Generating PDF financial report");

        try {

            Document document = new Document();

            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

            PdfWriter.getInstance(document, outputStream);

            document.open();

            // Title
            Font titleFont = FontFactory.getFont(
                    FontFactory.HELVETICA_BOLD,
                    20
            );

            Paragraph title = new Paragraph(
                    "FinanceOS Financial Report",
                    titleFont
            );

            title.setAlignment(Element.ALIGN_CENTER);

            document.add(title);

            // Space
            document.add(new Paragraph(" "));

            // Generated Date
            Paragraph date = new Paragraph(
                    "Generated On : " + LocalDate.now()
            );

            date.setAlignment(Element.ALIGN_RIGHT);

            document.add(date);

            document.add(new Paragraph(" "));

            // Report Table
            PdfPTable table = new PdfPTable(2);
            table.setWidthPercentage(100);

            table.addCell(new PdfPCell(new Phrase("Total Income")));
            table.addCell(new PdfPCell(new Phrase("₹ " + report.getTotalIncome())));

            table.addCell(new PdfPCell(new Phrase("Total Expense")));
            table.addCell(new PdfPCell(new Phrase("₹ " + report.getTotalExpense())));

            table.addCell(new PdfPCell(new Phrase("Total Savings")));
            table.addCell(new PdfPCell(new Phrase("₹ " + report.getTotalSavings())));

            table.addCell(new PdfPCell(new Phrase("Net Worth")));
            table.addCell(new PdfPCell(new Phrase("₹ " + report.getNetWorth())));

            table.addCell(new PdfPCell(new Phrase("Financial Health")));
            table.addCell(new PdfPCell(new Phrase(report.getFinancialHealth())));

            document.add(table);

            document.add(new Paragraph(" "));

            // Footer
            Paragraph footer = new Paragraph(
                    "Generated by FinanceOS v1.0"
            );

            footer.setAlignment(Element.ALIGN_CENTER);

            document.add(footer);

            document.close();

            logger.info("PDF financial report generated successfully");

            return outputStream.toByteArray();

        } catch (Exception e) {

            logger.error("Failed to generate PDF financial report", e);

            throw new RuntimeException("Failed to generate PDF", e);

        }
    }
}